In [2]:
import pickle

import numpy as np
import pandas as pd

In [3]:
with open(f"./learned_model.pkl", "rb") as f:
    learned_model = pickle.load(f)


qpos_result = np.hstack([learned_model["qpos_min"].reshape(-1,1), learned_model["qpos_max"].reshape(-1,1)])
qvel_result = np.hstack([learned_model["qvel_min"].reshape(-1,1), learned_model["qvel_max"].reshape(-1,1)])

In [5]:
df_qpos = pd.DataFrame(
    qpos_result,
    index = ["x", "y", "z", "qw", "qx", "qy", "qz", "hip1", "ankle1", "hip2", "ankle2", "hip3", "ankle3", "hip4", "ankle4"],
    columns=["qpos_min", "qpos_max"])
df_qpos.head(15)

        qpos_min   qpos_max
x      -0.218286  19.607769
y      -3.619194  19.338900
z       0.220410   1.105681
qw     -0.341288   0.999977
qx     -0.974721   0.993358
qy     -0.997668   0.985695
qz     -0.260520   0.999614
hip1   -0.663243   0.656203
ankle1 -0.099946   1.327814
hip2   -0.661253   0.665058
ankle2 -1.297224   0.099763
hip3   -0.658905   0.666901
ankle3 -1.328539   0.099308
hip4   -0.656940   0.657522
ankle4 -0.099567   1.334417

In [6]:
df_qvel = pd.DataFrame(
    qvel_result,
    index=["x_dot", "y_dot", "z_dot", "qx_dot", "qy_dot", "qz_dot", "hip1_dot", "ankle1_dot", "hip2_dot", "ankle2_dot", "hip3_dot", "ankle3_dot", "hip4_dot", "ankle4_dot"],
    columns=["qvel_min", "qvel_max"])
df_qvel.head(15)

            qvel_min  qvel_max
x_dot      -3.401052  3.688494
y_dot      -3.358296  3.611576
z_dot      -2.954137  3.299856
qx_dot     -4.542552  5.111098
qy_dot     -4.978244  4.894792
qz_dot     -4.584366  4.552562
hip1_dot   -7.465603  6.997549
ankle1_dot -6.009437  5.634026
hip2_dot   -7.119164  7.406900
ankle2_dot -5.527196  6.141526
hip3_dot   -7.221264  7.506518
ankle3_dot -5.752081  6.104660
hip4_dot   -6.986915  7.220225
ankle4_dot -6.136118  6.158838